version: '3'

services:
  ubuntu:
    build:
        context: ./
        dockerfile: ./docker/Dockerfile
    volumes:
        - ./src:/home/dev
    tty: true
    container_name: ubuntu-change-user-test